{% set name = "desktop-app" %}
{% set version = "0.4.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 7793e41b2764840d8f55444b320d721d203c0d156305ec36789eb0cc61c9ef20
  patches:
    - no_require_setuptools_scm_at_runtime.patch

build:
  number: 1
  script:
    - {{ PYTHON }} -m pip install . -vv --no-build-isolation
  entry_points:
    - desktop-app = desktop_app.__main__:main

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
    - {{ compiler('cxx') }}
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
  host:
    - python
    - pip
    - setuptools
    - setuptools-scm
  run:
    - python
    - setuptools-scm
    - importlib-metadata
    - pywin32                                # [win]
    - distlib

test:
  requires:
    - pip
  imports:
    - desktop_app
  commands:
    - desktop-app --help
    - pip check

about:
  home: https://pypi.org/project/desktop-app/
  license: BSD-2-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Simplify making a Python GUI application.
  description: |
    desktop-app simplifies making a Python GUI application install, launch, and
    behave in a standard way with respect to the application menus and the
    taskbar in Windows and Linux (Macos support planned).

  dev_url: https://github.com/chrisjbillington/desktop-app

extra:
  recipe-maintainers:
    - hmaarrfk
