{% set name = "desktop-app" %}
{% set version = "0.2.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: a74a44ce13ae05f8c4c7e079735bb01a9d5a8e3da32259fe114a6f0d1761b19f

build:
  number: 0
  script:
    - rm pyproject.toml
    - {{ PYTHON }} -m pip install . -vv
  entry_points:
    - desktop-app = desktop_app.__main__:main

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
  host:
    - python
    - pip
    - setuptools-scm
  run:
    - python
    - setuptools-scm
    - importlib-metadata
    - pywin32  # [win]
    - distlib

test:
  imports:
    - desktop_app
  commands:
    - desktop-app --help

about:
  home: https://pypi.org/project/desktop-app/
  license: BSD-2-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Simplify making a Python GUI application.
  description: |
    desktop-app simplifies making a Python GUI application install, launch, and
    behave in a standard way with respect to the application menus and the
    taskbar in Windows and Linux (Macos support planned).

  dev_url: https://github.com/chrisjbillington/desktop-app

extra:
  recipe-maintainers:
    - hmaarrfk
